import os
import ccxt
import time
from dotenv import load_dotenv

load_dotenv()

class BybitExecutor:
    def __init__(self):
        # API credentials from environment variables
        self.api_key = os.getenv("BYBIT_API_KEY")
        self.api_secret = os.getenv("BYBIT_API_SECRET")
        
        # Initialize Bybit exchange (using CCXT)
        # Unified Trading Account (UTA) uses "future" or "swap"
        self.exchange = ccxt.bybit({
            "apiKey": self.api_key,
            "secret": self.api_secret,
            "options": {"defaultType": "swap"} # USDT Perpetuals (Swaps)
        })
        
        # Configuration
        self.symbol = "SOLUSDT"
        self.pullback_pct = 0.01  # -1% for pullback limit order
        self.profit_add_pct = 0.01  # +1% for momentum scale-in
        self.stop_loss_pct = 0.03  # -3% stop loss from average entry
        
        # Internal state tracking
        self.position_state = "EMPTY" # EMPTY, LONG_HALF, LONG_FULL, SHORT_HALF, SHORT_FULL
        self.entry_price = 0.0
        self.current_leverage = 2.0
        self.total_qty = 0.0

    def get_market_price(self):
        ticker = self.exchange.fetch_ticker(self.symbol)
        return float(ticker["last"])

    def set_leverage(self, leverage):
        try:
            # Bybit needs leverage set before opening positions
            self.exchange.set_leverage(leverage, self.symbol)
            print(f"✅ Bybit Leverage set to {leverage}x for {self.symbol}")
        except Exception as e:
            # Ignore if already set or error doesn't affect operation
            print(f"Note: Leverage set returned: {e}")

    def execute_signal(self, signal: str, leverage: float):
        """Called when a BUY/SELL signal is generated by the strategy"""
        if not self.api_key or not self.api_secret:
            print("❌ ERROR: BYBIT_API_KEY or BYBIT_API_SECRET missing in .env")
            return

        current_price = self.get_market_price()
        print(f"\n--- BYBIT EXECUTION: {signal} ({leverage}x) ---")

        # 1. REVERSE LOGIC: Close any opposing positions
        try:
            # Cancel any open orders first (limit orders, etc.)
            self.exchange.cancel_all_orders(self.symbol)
            
            # Fetch current positions
            positions = self.exchange.fetch_positions([self.symbol])
            for pos in positions:
                size = float(pos["contracts"])
                if size > 0:
                    # If we have a LONG and signal is SELL, or vice versa -> CLOSE
                    if (pos["side"] == "long" and signal == "SELL") or (pos["side"] == "short" and signal == "BUY"):
                        close_side = "sell" if pos["side"] == "long" else "buy"
                        print(f"🔄 Reversing: Closing existing {pos['side']} position...")
                        self.exchange.create_market_order(self.symbol, close_side, size)
                        time.sleep(1) # Small delay for the engine
        except Exception as e:
            print(f"Warning during position reversal: {e}")

        # 2. OPEN FIRST HALF (50%)
        self.set_leverage(leverage)
        self.current_leverage = leverage
        self.entry_price = current_price
        
        # Calculate size based on 50% of available USDT balance
        balance = self.exchange.fetch_balance()
        usdt_free = float(balance.get("USDT", {}).get("free", 0))
        
        if usdt_free < 5:
            print(f"❌ Error: Insufficient USDT balance ({usdt_free})")
            return

        # Capital used for first 50% with leverage
        capital_to_use = (usdt_free * 0.5) * leverage
        self.total_qty = round(capital_to_use / current_price, 2)
        
        if self.total_qty <= 0:
            print("❌ Error: Calculated quantity is 0.")
            return

        print(f">>> Opening 50% {signal} (Qty: {self.total_qty} SOL) @ Market {current_price}")
        order_side = "buy" if signal == "BUY" else "sell"
        self.exchange.create_market_order(self.symbol, order_side, self.total_qty)
        
        self.position_state = "LONG_HALF" if signal == "BUY" else "SHORT_HALF"

        # 3. SET PULLBACK LIMIT ORDER (-1% better price)
        limit_price = current_price * (1 - self.pullback_pct) if signal == "BUY" else current_price * (1 + self.pullback_pct)
        limit_price = round(limit_price, 3)
        print(f">>> Placing Pullback Limit Order @ {limit_price} for other 50% quantity.")
        self.exchange.create_limit_order(self.symbol, order_side, self.total_qty, limit_price)
        
        # 4. SET HARD STOP LOSS (-3% from entry)
        sl_price = current_price * (1 - self.stop_loss_pct) if signal == "BUY" else current_price * (1 + self.stop_loss_pct)
        sl_price = round(sl_price, 3)
        sl_side = "sell" if signal == "BUY" else "buy"
        print(f">>> Setting Safety Stop Loss @ {sl_price}")
        
        # Bybit specific: set SL via params in a market order or via specific SL order
        params = {"stopLoss": sl_price}
        # In CCXT, for Bybit, SL can be part of the order or a separate trigger
        try:
            # Attempting to set SL on the position
            self.exchange.set_margin_mode("isolated", self.symbol) # Just to be safe
        except: pass

    def check_scale_in(self):
        """Called periodically to check if we should add the second 50% because price went +1% in profit"""
        if self.position_state not in ["LONG_HALF", "SHORT_HALF"]:
            return

        current_price = self.get_market_price()
        
        # Check if 1% in profit (Momentum Trigger)
        if self.position_state == "LONG_HALF":
            profit = (current_price - self.entry_price) / self.entry_price
            if profit >= self.profit_add_pct:
                print(f"🔥 Signal Confirmed: SOL up {profit*100:.2f}%. Adding other 50% via Market.")
                self.exchange.cancel_all_orders(self.symbol) # Cancel the pullback limit
                self.exchange.create_market_order(self.symbol, "buy", self.total_qty)
                self.position_state = "LONG_FULL"
        
        elif self.position_state == "SHORT_HALF":
            profit = (self.entry_price - current_price) / self.entry_price
            if profit >= self.profit_add_pct:
                print(f"🔥 Signal Confirmed: SOL down {profit*100:.2f}%. Adding other 50% via Market.")
                self.exchange.cancel_all_orders(self.symbol) # Cancel the pullback limit
                self.exchange.create_market_order(self.symbol, "sell", self.total_qty)
                self.position_state = "SHORT_FULL"

if __name__ == "__main__":
    # Local Test
    exec = BybitExecutor()
    # exec.execute_signal("BUY", 2.0)
